#ifndef sprite_block_interaction_types_h
#define sprite_block_interaction_types_h

typedef struct SpriteBlockPositionedInteraction SpriteBlockPositionedInteraction;
typedef struct SpriteBlockInteractionResult SpriteBlockInteractionResult;

#endif /* sprite_block_interaction_types_h */
